sudo: required

services:
  - docker

before_install:
  - docker image build --tag juliocesarmidia/client-tests:latest -f ./__tests__/Dockerfile ./__tests__

script:
  - docker container run juliocesarmidia/client-tests:latest

# after_success:
#   - docker image build --tag juliocesarmidia/client-wrapper:latest ./client

  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # - docker image push juliocesarmidia/client-wrapper:latest
