version: '3.4'

services:
  client:
    build:
      context: ./client
      dockerfile: development.Dockerfile
      args:
        VUE_APP_CLIENT_ID: ${VUE_APP_CLIENT_ID}
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - DEV_TOOLS=true
