version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - /app/node_modules
      - ./client:/app
    environment: 
      - DEV_TOOLS=false
  dev:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./client:/app
    environment: 
      - DEV_TOOLS=true
  tests:
    build:
      context: ./__tests__
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./__tests__:/app
